config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  resources :objets, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } do
    resources :encheres
    collection do
      get 'ventes'
      get 'achats'
    end
  end


  resources :utilisateurs, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } do
    resources :commentaires
  end
  resources :categories, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ }



  #rename path for session (create new session or pagge for new session = login, delete session = logout)
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'home#index'
end

app/models/utilisateur.rb
require 'bcrypt'
class Utilisateur < ApplicationRecord
  attr_accessor :token #give access to this attribute

  #assoications for commentaire table , create 2 foreign key
  has_many :etrecomments, :class_name => 'Commentaire', :foreign_key => 'uti_becomment_id'
  has_many :comments, :class_name => 'Commentaire', :foreign_key => 'utilisateur_id'
  #user could have multiples objects and bids
  has_many :objets
  has_many :encheres

  validates :nomuti, presence: true
  validates :prenomuti, presence: true
  validates :age, presence: true
  validates :login, presence: true, uniqueness: true

  #password_digest create with this function : secure the password
  validates :password, presence: true, length: {minimum: 6}
  has_secure_password

  # given the password_digest hash
  def digest(string)
    #create a cost witch is use for has password
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                      BCrypt::Engine.cost
    #create password with cost
    BCrypt::Password.create(string, cost: cost)
  end


  # create de new token
  def new_token
    SecureRandom.urlsafe_base64
  end

  #give to remember token for remember utilisateur
  def remember
    self.token = new_token
    #store a condensed of the token
    update_attribute(:remember_digest, digest(token))
  end

  #verifie if the token = remember_digest
  def authenticated(token)
    #test if the attribute remmenber_digest is nil in the bd
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(token)
  end

  def forgetting
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
#not acces to page if not connect
 before_action :set_utilisateur, only: [:edit, :update, :destroy, :show]

 before_action :autorized, only: [:update, :edit, :show]

  def new
    @utilisateur= Utilisateur.new
  end

  def create

    @utilisateur = Utilisateur.new(utilisateur_params)
    @utilisateur.remember
    @utilisateur.save
    logIn @utilisateur
    remember @utilisateur

    respond_to do |format|
      format.html {render :show}
      format.json {render :show }
    end

  end

  def update
    current_user.update(utilisateur_params)

    respond_to do |format|
      format.html {render :show}
      format.json {render :show }
    end

  end

 def edit
  #to_s because param[:id] is a string
   if (params[:id] == current_user.id.to_s)
     render(:edit)
   else
     #non authorized to access to other user modification profile
     render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
   end
 end

 def show
   if (params[:id] == current_user.id.to_s)
     render(:show)
   else
     #non authorized to access to other user's profile
     render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
   end
 end
  private
  def utilisateur_params
    params.require(:utilisateur).permit(:nomuti, :prenomuti, :login, :password, :age, :rue, :codepostal, :ville)
  end

  def set_utilisateur
    @utilisateur=current_user
  end
end

app/helpers/utilisateur_helper.rb
module UtilisateurHelper
end

app/views/utilisateurs/edit.html.erb
<div class="container">
  <h2 class="titre2">Modification du profil</h2>

  <%= form_with scope: :utilisateur, url: utilisateur_path(current_user), html: {method: :put}, local: true do |form| %>
    <div class="contact-form">
      <div class="col-md-10">
        <%= form.label :nom, "Nom" %><br/>
        <%= form.text_field :nomuti, :required => true %>
      </div>
      <div class="col-md-10">
        <%= form.label :prenom, "Prenom" %><br/>
        <%= form.text_field :prenomuti, :required => true %>
      </div>
      <div class="col-md-10">
        <%= form.label :age, "Age" %><br/>
        <%= form.text_field :age, :required => true %>
      </div>
      <div class="col-md-10">
        <p>Adresse</p>
        <%= form.label :rue, "Rue" %><br/>
        <%= form.text_field :rue, :required => true %><br/>
        <%= form.label :codepostal, "Code postal" %><br/>
        <%= form.number_field :codepostal, :required => true %><br/>
        <%= form.label :ville, "Ville" %><br/>
        <%= form.text_field :ville, :required => true %>
      </div>
      <div class="col-md-10">
        <%= form.label :login, "Adresse mail" %><br/>
        <%= form.email_field :login, :required => true %>
      </div>
      <div class="col-md-10">
        <%= form.label :password_digest, "Mot de passe (6 caractères minimum)" %><br/>
        <%= form.password_field :password, :required => true , :autocomplete => 'off' %>
        <%= form.submit :valider %>
      </div>

    </div>
    </div>
    </form>
    </div>
  <% end %>

app/views/utilisateurs/new.html.erb
<div class="container">
  <h2 class="titre2">Inscription</h2>

  <%= form_with scope: :utilisateur, url: utilisateurs_path, local: true do |form| %>
    <div class="contact-form">
      <div class="col-md-10">
        <%= form.label :nom, "Nom" %><br/>
        <%= form.text_field :nomuti, :required => true %>
      </div>
      <div class="col-md-10">
        <%= form.label :prenom, "Prenom" %><br/>
        <%= form.text_field :prenomuti, :required => true %>
      </div>
      <div class="col-md-10">
        <%= form.label :age, "Age" %><br/>
        <%= form.text_field :age, :required => true %>
      </div>
      <div class="col-md-10">
        <p>Adresse</p>
        <%= form.label :rue, "Rue" %><br/>
        <%= form.text_field :rue, :required => true %><br/>
        <%= form.label :codepostal, "Code postal" %><br/>
        <%= form.number_field :codepostal, :required => true %><br/>
        <%= form.label :ville, "Ville" %><br/>
        <%= form.text_field :ville, :required => true %>
      </div>
      <div class="col-md-10">
        <%= form.label :login, "Adresse mail" %><br/>
        <%= form.email_field :login, :required => true %>
      </div>
      <div class="col-md-10">
        <%= form.label :password, "Mot de passe (6 caractères minimum)" %><br/>
        <%= form.password_field :password, :required => true, :minlength => '6', :autocomplete => 'off' %>
        <%= form.submit :valider %>
      </div>

      </div>
    </div>
    </form>
    </div>
  <% end %>

app/views/utilisateurs/show.html.erb
<div class="container">
  <div class="header-page header-img" >
    <div class="col-md-6 col-md-offset-6">
      <div class="row">
        <div class="inner-content-compte">
          <div class="header-content">
            <h1> Mon profil </h1>
            <hr>
            <p>Informations personnelles</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <h2 class="titre2">Profil</h2>
  <div class="col-md-5" id="ident">
    <p id="libProfil"><strong>Identité :</strong></p><br/>
    <p id="identity"> <%= @utilisateur.nomuti %>
     <%= @utilisateur.prenomuti %> <br/></p>
    <p><strong>Age :</strong></p>
     <%= @utilisateur.age %>
    </div>

  <div class="col-md-5" id="contact">
   <p id="libProfil"><strong>Contact :</strong></p><br/>
    <p ><strong>Mail :</strong></p><br/>
    <p id="identity"> <%= @utilisateur.login %></p>
    <p><strong>Adresse :</strong></p><br/>
    <p id="identity"> <%= @utilisateur.rue %><br/>
    <%= @utilisateur.codepostal %><br/>
    <%= @utilisateur.ville %></p>
   </div>
</div>
<% if logged_in %>
    <div class="col-md-12" id="divButtonProf">
      <div class="buttonModif">
        <%= link_to "Modifier", edit_utilisateur_path(current_user), {:class => "alink"} %>
      </div>
    </div>
 <% end %>