config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  resources :objets, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } do
    resources :encheres
    collection do
      get 'ventes'
      get 'achats'
    end
  end


  resources :utilisateurs, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } do
    resources :commentaires
  end
  resources :categories, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ }



  #rename path for session (create new session or pagge for new session = login, delete session = logout)
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @objets= Objet.where("datefinench > ?" , DateTime.now).order(created_at: :asc).last(6)
    @categories= Categorie.all

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">

  <!-- Slide -->
  <div class="container">
    <div class="header-page header-img">
      <div class="col-md-6 col-md-offset-6">
        <div class="row">
          <div class="inner-content-compte">
            <div class="header-content">
              <h1>Encher'O max</h1>
              <hr>
              <p>Site de vente entre particuliers</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Page Heading -->

  <!--categorie navigation-->

  <div class="container margin-top">
    <div class="portfolio-wrapper">
      <button class="nav">
                <span class="icon-container">
				<span class="line line01"></span>
                <span class="line line02"></span>
                <span class="line line03"></span>
                <span class="line line04"></span>
                </span>
      </button>
      <div class="works-filter">
        <%= link_to "All", objets_path, :class => "filter active" %>
        <% @categories.each do |categorie| %>
            <%= link_to  category_path(categorie.id), :class => "filter active"  do %>
               <%= categorie.nomcategorie.capitalize %>
            <% end %>
          <% end %>

      </div>
      <!--container-->
      <div class="row" id="work-grid">
        <% @objets.each do |objet| %>
        <div class="col-md-4 col-sm-4 col-xs-12 mix music">
          <div class="img home-portfolio-image">
            <%= cl_image_tag("#{objet.id}.jpg",alt: objet.nomobjet, height: '300px') %>
            <div class="overlay-thumb">
              <a href="javascript:void(0)" class="like-product">
                <i class="ion-ios-heart-outline"></i>
                <span class="output"><%=objet.categorie.nomcategorie.capitalize %></span>
              </a>
              <div class="details">
                <span class="title"><%=objet.nomobjet %></span>


                <span class="info"><%= objet.encheres.length > 0 ? objet.encheres.last.prix : objet.prix %>0 €</span>





              </div>
              <span class="btnBefore"></span>
              <span class="btnAfter"></span>
              <%= link_to "", objet_path(objet.id), {:class => "main-portfolio-link"} %>
            </div>
          </div>
        </div>
        <% end %>

      </div>


      <!-- Pagination -->
     <ul class="pagination justify-content-center">

      </ul>

    </div>
  </div>
</div>
<!-- /.container -->