config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  resources :objets, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } do
    resources :encheres
    collection do
      get 'ventes'
      get 'achats'
    end
  end


  resources :utilisateurs, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } do
    resources :commentaires
  end
  resources :categories, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ }



  #rename path for session (create new session or pagge for new session = login, delete session = logout)
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'home#index'
end

app/models/objet.rb
class Objet < ApplicationRecord

  belongs_to :categorie
  belongs_to :utilisateur
  #an object could have mutiple bids

  # dependent detroy => delete enchere of objets
  has_many :encheres, dependent: :destroy

  validates :nomobjet, presence: true
  validates :prix, presence: true
  validates :description, presence: true
  validates :datefinench, presence: true
  validates :categorie_id, presence: true
  validates :utilisateur_id, presence: true
end

app/controllers/objets_controller.rb
class ObjetsController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:destroy]
  before_action :autorized, only: [:update, :edit, :ventes, :new, :achats, :destroy]

  def new
    @objet=Objet.new
    @categories= Categorie.all
  end

def index
  @categories= Categorie.all
  @objets= Objet.where("datefinench > ?" , DateTime.now)

end


def show
  @objet = Objet.find(params[:id])

  #if not on the market redirection
  if (@objet.datefinench < DateTime.now)
    render(:file => File.join(Rails.root, 'public/Plusenvente.html'), :status => 302, :layout => false)
  else
    @enchere=Enchere.where( objet_id: @objet.id).last
    if @enchere == nil
      @prix = @objet.prix
    else
      @prix = @enchere.prix
    end
  end
end

  def create

    @objet = current_user.objets.new(objet_params)
    @objet.save

    if (params[:objet][:photo] != nil)

      #save the name of image in the database
      @objet.update( photo: @objet.id.to_s)

      begin
        #upload image on cloud
        Cloudinary::Uploader.upload(params[:objet][:photo], :public_id => @objet.id.to_s)
        respond_to do |format|
             format.html {render 'objets/show'}
             format.json {render :show}
        end
      rescue Exception
        flash[:warning] = 'Fichier non valide'
        redirect_to  new_objet_path
      end

    end

  end

  def update
    @objet = Objet.find(params[:id])
    @objet.update(objet_params)

    #recover image in images folder
    if (params[:objet][:photo] != nil)

      #save the name of image in the database
      @objet.update( photo: @objet.id.to_s)

      begin
        #upload image on cloud
        Cloudinary::Uploader.upload(params[:objet][:photo], :public_id => @objet.id.to_s)
        respond_to do |format|
             format.html {render :show}
             format.json {render :show }
        end
      rescue Exception
        flash[:warning] = 'Fichier non valide'
        redirect_to  edit_objet_path
      end


    else
      redirect_to  objet_path
    end
  end

  def edit
    @categories= Categorie.all
    #find object information
    @objet = Objet.find(params[:id])

    #if the usr is not the seller of object 403
    if  current_user.id!= @objet.utilisateur_id
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  def destroy
    @objet = Objet.find(params[:id])

    if  current_user.id!= @objet.utilisateur_id
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    else
      id = @objet.id
      #delete object, create json response for delete object in the page
      @objet.destroy
      render json: {id: id}
    end

  end

  def ventes
    #object which are on the market
    @objets= Objet.where( utilisateur_id: current_user.id).where("datefinench > ?" , DateTime.now)
    #sold object or object which datefinench is passed
    @objets2= Objet.where( utilisateur_id: current_user.id).where("datefinench < ?" , DateTime.now)
  end

  def achats
    #object which are on the market and user have bids on it
    @objets = []
    Objet.where.not(utilisateur_id: current_user.id).where("datefinench > ?" , DateTime.now).each do |o|
      @objets << o if o.encheres.pluck(:utilisateur_id).include?(current_user.id)
    end

    @objets2 = []
    #sold object or object which datefinench is passed an the last bids was made by user
    Objet.where.not( utilisateur_id: current_user.id).where("datefinench < ?" , DateTime.now).each do |o|
      @objets2 << o if o.encheres.last.utilisateur.id == current_user.id
    end

  end
  private
    def objet_params

      params.require(:objet).permit(:nomobjet, :prix, :description, :datefinench , :categorie_id)

    end
  end

app/views/objets/achats.html.erb
<div class="container">

  <!-- Slide -->
  <div class="container">
    <div class="header-page header-img">
      <div class="col-md-6 col-md-offset-6">
        <div class="row">
          <div class="inner-content-compte">
            <div class="header-content">
              <h1>Mes objets</h1>
              <hr>
              <p>Retrouvez les objets sur lesquels vous avez enchéri</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- Page Heading -->

  <!--categorie navigation-->

  <div class="container margin-top">
    <div class="portfolio-wrapper">

      <!--container-->
      <div class="row" id="work-grid">
        <h5 class="objSousTitre">Les objets qui vous intéressent</h5>
        <% @objets.each do |objet| %>
          <div class="col-md-4 col-sm-4 col-xs-12 mix music">
            <div class="img home-portfolio-image">
              <%= cl_image_tag("#{objet.id}.jpg",alt: objet.nomobjet) %>
              <div class="overlay-thumb">
                <a href="javascript:void(0)" class="like-product">
                  <i class="ion-ios-heart-outline"></i>
                  <span class="output"><%= objet.categorie.nomcategorie.capitalize %></span>
                </a>
                <div class="details buttonVente">
                  <span class="modifV"> <%= link_to "Voir l'objet", objet_path(objet.id), {:class => "linkOM"} %></span><br/>
                  <span class="modifV"> <%= link_to "Listes des encheres", objet_encheres_path(objet.id), {:class => "linkOM"} %></span><br/>
                  <span class="deletV"> <%= link_to "Enchérir", new_objet_enchere_path(objet.id), {:class => "linkOM"} %></span><br/>
              </div>

                <div class="details">
                  <span class="title"><%= objet.nomobjet %></span>
                  <span class="info"><%= objet.encheres.length > 0 ? objet.encheres.last.prix : objet.prix %>0 €</span>
                </div>
                <span class="btnBefore"></span>
                <span class="btnAfter"></span>
              </div>
            </div>
          </div>
        <% end %>

      </div>
      <div class="row">
        <h5 class="objSousTitre">Les objets achetés</h5>
      </div>
      <div class="row" id="work-grid">
        <% @objets2.each do |objet| %>
          <% if objet.encheres.last.utilisateur_id == current_user.id %>
          <div class="col-md-4 col-sm-4 col-xs-12 mix music">
            <div class="img home-portfolio-image">
              <%= cl_image_tag("#{objet.id}.jpg",alt: objet.nomobjet) %>
              <div class="overlay-thumb">
                <a href="javascript:void(0)" class="like-product">
                  <i class="ion-ios-heart-outline"></i>
                  <span class="output"><%= objet.categorie.nomcategorie.capitalize %></span>
                </a>

                <div class="details buttonVente">
                  <span class="modifV"> <%= link_to "Commenter le vendeur", new_utilisateur_commentaire_path(objet.utilisateur.id), {:class => "linkOM"} %></span><br/>
                </div>

                <div class="details">
                  <span class="title"><%= objet.nomobjet %></span>
                  <span class="info"><%= objet.encheres.length > 0 ? objet.encheres.last.prix : objet.prix %>0 €</span>
                </div>
                <span class="btnBefore"></span>
                <span class="btnAfter"></span>
              </div>
            </div>
          </div>
            <% end %>
        <% end %>
      </div>


      <ul class="pagination justify-content-center">

      </ul>

    </div>
  </div>
</div>
<!-- /.container -->

app/views/objets/edit.html.erb
<div class="container">
  <h2 class="titre2"> Modifier un objet</h2>
  <span class="warning"><%= flash[:warning] %></span></div>
  <%= form_with scope: :objet, url: objet_path(@objet.id), html: {method: :put}, local: true do |form| %>
    <div class="contact-form">
      <div class="col-md-10">
        <%= form.label :nomobjet, "Nom" %><br>
        <%= form.text_field :nomobjet %>
      </div>
      <div class="col-md-10">
        <%= form.label :categorie_id, "Categorie de l'objet" %><br>
        <%= form.select(:categorie_id, @categories.map {|categorie| [categorie.nomcategorie,categorie.id]}) %>
      </div>
      <div class="col-md-10">
        <%= form.label :prix, "Prix de départ des enchères" %><br>
        <%= form.number_field :prix, :disabled => true %>
      </div>
      <div class="col-md-10 col-sm-5">
        <%= form.label :photo, "Photo de l'objet" %><br>
        <%= form.file_field :photo, accept: 'image/jpeg'  %>
      </div>
      <div class="col-md-10 col-sm-5">
        <%= form.label :datefinench, "Date de fin des enchères" %><br>
        <%= form.datetime_local_field :datefinench, min: Date.today  %>
      </div>
      <div class="col-md-10">
        <%= form.label :description, "Description" %><br>
        <%= form.text_area :description %>
        <%= form.submit :valider %>
      </div>
    </div>
    </div>
  <% end %>

app/views/objets/index.html.erb
<div class="container">

  <!-- Slide -->
  <div class="container">
    <div class="header-page header-img">
      <div class="col-md-6 col-md-offset-6">
        <div class="row">
          <div class="inner-content-compte">
            <div class="header-content">
              <h1>Objets en vente</h1>
              <hr>
              <p>Retrouvez tous nos objets disponibles</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- Page Heading -->

  <!--categorie navigation-->

  <div class="container margin-top">
    <div class="portfolio-wrapper">
      <button class="nav">
                <span class="icon-container">
				<span class="line line01"></span>
                <span class="line line02"></span>
                <span class="line line03"></span>
                <span class="line line04"></span>
                </span>
      </button>
      <div class="works-filter">
        <%= link_to "All", objets_path, :class => "filter active" %>
        <% @categories.each do |categorie| %>
          <%= link_to category_path(categorie.id), :class => "filter active" do %>
            <%= categorie.nomcategorie.capitalize %>
          <% end %>
        <% end %>

      </div>
      <!--container-->
      <div class="row" id="work-grid">
        <% @objets.each do |objet| %>
          <div class="col-md-4 col-sm-4 col-xs-12 mix music">
            <div class="img home-portfolio-image">
              <%= cl_image_tag("#{objet.id}.jpg",alt: objet.nomobjet) %>
              <div class="overlay-thumb">
                <a href="javascript:void(0)" class="like-product">
                  <i class="ion-ios-heart-outline"></i>
                  <span class="output"><%= objet.categorie.nomcategorie %></span>
                </a>
                  <div class="details">
                  <span class="title"><%= objet.nomobjet %></span>
                  <span class="info"><%= objet.encheres.length > 0 ? objet.encheres.last.prix : objet.prix %>0 €</span>
                </div>
                <span class="btnBefore"></span>
                <span class="btnAfter"></span>
                <%= link_to "", objet_path(objet.id), {:class => "main-portfolio-link"} %>
              </div>
            </div>
          </div>
        <% end %>

      </div>


      <ul class="pagination justify-content-center">

      </ul>

    </div>
  </div>
</div>
<!-- /.container -->

app/views/objets/new.html.erb
<div class="container">
  <h2 class="titre2"> Vendre un objet</h2>
  <%= flash[:warning] %>

  <%= form_with scope: :objet, url: objets_path, local: true do |form| %>
    <div class="contact-form">
        <div class="col-md-10">
          <%= form.label :nomobjet, "Nom" %><br>
          <%= form.text_field :nomobjet %>
        </div>
       <div class="col-md-10">
         <%= form.label :categorie_id, "Categorie de l'objet" %><br>
         <%= form.select(:categorie_id, @categories.map {|categorie| [categorie.nomcategorie,categorie.id]}) %>
        </div>
        <div class="col-md-10">
          <%= form.label :prix, "Prix de départ des enchères" %><br>
          <%= form.number_field :prix %>
        </div>
        <div class="col-md-10 col-sm-5">
          <%= form.label :photo, "Photo de l'objet" %><br>
          <%= form.file_field :photo, accept: 'image/jpeg' %>
        </div>
        <div class="col-md-10 col-sm-5">
          <%= form.label :datefinench, "Date de fin des enchères" %><br>
          <%= form.datetime_local_field :datefinench, min: Date.today, :value => Time.zone.now.advance(weeks: 4).strftime("%Y-%m-%dT%H:%M") %>
       </div>
        <div class="col-md-10">
          <%= form.label :description, "Description" %><br>
          <%= form.text_area :description %>
          <%= form.submit :valider %>
        </div>
      </div>
    </div>
  <% end %>

app/views/objets/show.html.erb
<div class="container">
  <h2 class="titre2"><%= @objet.nomobjet %></h2>
  <p class="vendeur"> Vendeur : <%= @objet.utilisateur.prenomuti %> <%= @objet.utilisateur.nomuti %></p>
  <span class="comment_show"><%= link_to "Voir les commentaires sur le vendeur", utilisateur_commentaires_path(@objet.utilisateur.id) %></span>
  <div class="col-md-5" id="photoObj">
    <%= cl_image_tag("#{@objet.id}.jpg",alt: @objet.nomobjet, height: '250px' ) %>
  </div>

  <div class="col-md-5" id="infoObj">
    <p ><strong>Prix initial:  <%= @objet.prix %>0 € </strong></p><br/>

      <p ><strong>Prix actuel:  <%= @prix%>0 € </strong></p><br/>

    <p ><strong>Date de fin d'enchère :  <%= @objet.datefinench.strftime("%d/%m/%Y %H:%M") %> </strong></p><br/>
    <p ><strong>Description :  <%= @objet.description %>  </strong></p><br/>
  </div>

</div>
<%if  logged_in %>
  <%if current_user.id==@objet.utilisateur.id %>
    <div class="col-md-12" id="divButtonObj">
      <div class="buttonModif">
        <%= link_to "Modifier", edit_objet_path(@objet.id), {:class => "alink"} %>
      </div>
    </div>
  <% else%>
    <div class="col-md-12" id="divButtonObj">
      <div class="buttonModif">
        <%= link_to "Encherir", new_objet_enchere_path(@objet.id), {:class => "alink"} %>
     </div>
    </div>

  <%end%>
<%end%>

app/views/objets/ventes.html.erb
<div class="container">

  <!-- Slide -->
  <div class="container">
    <div class="header-page header-img">
      <div class="col-md-6 col-md-offset-6">
        <div class="row">
          <div class="inner-content-compte">
            <div class="header-content">
              <h1>Mes objets</h1>
              <hr>
              <p>Retrouvez les objets que vous avez mis en vente</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- Page Heading -->

  <!--categorie navigation-->

  <div class="container margin-top">
    <div class="portfolio-wrapper">

      <!--container-->
      <div class="row" id="work-grid">
        <h5 class="objSousTitre">Les objets en vente</h5>
        <% @objets.each do |objet| %>
          <div class="col-md-4 col-sm-4 col-xs-12 mix music" id="<%= objet.id %>">
            <div class="img home-portfolio-image">
              <%= cl_image_tag("#{objet.id}.jpg",alt: objet.nomobjet) %>
              <div class="overlay-thumb">
                <a href="javascript:void(0)" class="like-product">
                  <i class="ion-ios-heart-outline"></i>
                  <span class="output"><%= objet.categorie.nomcategorie.capitalize %></span>
                </a>
                <div class="details buttonVente">
                  <span class="modifV"> <%= link_to "Liste des encheres", objet_encheres_path(objet.id),  {:class => "linkOM"} %></span><br/>
                  <span class="modifV"> <%= link_to "Modifier", edit_objet_path(objet.id),  {:class => "linkOM"} %></span><br/>
                  <span class="deletV "> <a class="linkOD" data-url="<%=objet_path(objet)%>">Supprimer</a></span>
                </div>

                  <div class="details">
                  <span class="title"><%= objet.nomobjet %></span>
                    <span class="info"><%= objet.encheres.length > 0 ? objet.encheres.last.prix : objet.prix %>0 €</span>
                </div>
                <span class="btnBefore"></span>
                <span class="btnAfter"></span>
              </div>
            </div>
          </div>
        <% end %>

      </div>
      <div class="row">
       <h5 class="objSousTitre">Les objets vendus ou plus en vente</h5>
      </div>
      <div class="row" id="work-grid">
        <% @objets2.each do |objet| %>
          <div class="col-md-4 col-sm-4 col-xs-12 mix music">
            <div class="img home-portfolio-image">
              <%= cl_image_tag("#{objet.id}.jpg",alt: objet.nomobjet) %>
              <div class="overlay-thumb">
                <a href="javascript:void(0)" class="like-product">
                  <i class="ion-ios-heart-outline"></i>
                  <span class="output"><%= objet.categorie.nomcategorie.capitalize %></span>
                </a>
                <div class="details">
                  <span class="title"><%= objet.nomobjet %></span>
                  <span class="info"><%= objet.encheres.length > 0 ? objet.encheres.last.prix : objet.prix %>0 €</span>
                </div>
                <span class="btnBefore"></span>
                <span class="btnAfter"></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>


      <ul class="pagination justify-content-center">

      </ul>

    </div>
  </div>
</div>
<!-- /.container -->