config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  resources :objets, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } do
    resources :encheres
    collection do
      get 'ventes'
      get 'achats'
    end
  end


  resources :utilisateurs, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ } do
    resources :commentaires
  end
  resources :categories, :constraints => { :id => /[0-9]+(\%7C[0-9]+)*/ }



  #rename path for session (create new session or pagge for new session = login, delete session = logout)
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <button id="op" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <button id="clo" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <% if logged_in %>
            <li class="nav-item nav-link">
              <%= link_to "Accueil", root_url %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to "Vendre", new_objet_path %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to "Mes achats", achats_objets_path %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to "Mes ventes", ventes_objets_path %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to "Mes commentaires", utilisateur_commentaires_path(current_user.id) %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to "Profil", current_user %>
            </li>
            <li class="nav-item nav-link">
              <%= link_to "Deconnexion", logout_path, method: :delete %>
            </li>

          <% else %>

            <li class="nav-item nav-link">
              <%= link_to "Accueil", root_url %>
            </li>

            <li class="nav-item nav-link">
              <%= link_to "Inscription", new_utilisateur_path %>
            </li>

            <li class="nav-item nav-link">
              <%= link_to "Connexion", login_path %>
            </li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>

    <%= yield %>

  </body>
</html>